steps:
- name: gcr.io/uber-container-tools/makisu:latest
  args: ['build', '--load', '--modifyfs=true', '-t', 'eu.gcr.io/dnl-gcb-wbaa-dap-sbx/dap/gcp-makisu-multistage-poc:latest' ,'--commit=explicit', '.']

# TODO: Instead of building with --load into the Docker daemon
# then pushing, use --push=gcr.io which will push directly to the
# registry and bypass the Docker daemon. Unfortunately, this seems
# to not work with Google's Application Default Credentials.

images:
- eu.gcr.io/dnl-gcb-wbaa-dap-sbx/dap/gcp-makisu-multistage-poc:latest
